### ISSUE TITLE
JSO not detect resizing when you modify display:grid; container

### ISSUE THREAD

**Issue by XCanG** [libass/JavascriptSubtitlesOctopus#33]
My page use template based on `display: grid;`, container for the video have 2 columns, one for video (wrapper), anothe for playlist items.

.video | .playlist
----- | --------

In Video wrapper on custom video controls I have expand button (analog is youtube widescreen button). Clicling on that button trigger JS function what add class to the player, this class change 2 rules for video wrapper: from `grid-column: 1; grid-row: 1;` to `grid-column: 1 / 3; grid-row: 1;`. 

.video | .video (expanded)
----- | --------

This action resize player, but JSO not resize canvas, however fullscreen button (toggle video wrapper element full screen mode) is working and it might be fixed by this action, so:
1. clicking expand button and expand grid position not trigger canvas resizing
2. clicking 2 times on full screen mode (when you back to normal mode) resizes canvas to their property value
3. clicking expand button again to retract player size again not trigger canvas resizing

**Comment by XCanG** [comment]
There may be also solution if manually resize window, but this is a trick.

**Comment by TFSThiagoBR98** [comment]
Can you send an example?

**Comment by Dador** [comment]
> Clicling on that button trigger JS function what add class to the player, this class change 2 rules for video wrapper: from grid-column: 1; grid-row: 1; to grid-column: 1 / 3; grid-row: 1;.

You can call `octopusInstance.resize()` (without arguments) after you changed video size. It'll trigger canvas resize and will fix that issue. You can also call it with `setTimeout` if you have resize animation.

Recently [Resize Observer](https://developers.google.com/web/updates/2016/10/resizeobserver) was introduced and it'll allow to resolve this problem without manually calling `resize()`, but currently it's supported only by Chrome. It's also possible to use polyfill (typically based on checking size of element every X ms which shouldn't be a big problem in case of one element as in our case).

**Comment by XCanG** [comment]
Example:
HTML:
```html
<div class="wrap">
    <div class="video">
        <div class="controls">
            <div class="...">...</div>
            ...
        </div>
    </div>
    <div class="playlist"></div>
</div>
```
video tag insert at te first play later when first file in playlist are selected,
CSS:
```css
/* ... other styles, parent styles... */
.wrap { grid-area: player; grid-template-columns: 1fr 400px; grid-template-rows: 1fr; align-content: stretch; justify-content: stretch; }

.video { grid-column: 1; grid-row: 1; background: #000000; -webkit-user-select: none; -moz-user-select: none; user-select: none; font-size: 16pt; font-weight: 300; white-space: nowrap; grid-template-columns: 1fr; grid-auto-columns: auto; position: relative; display: block; overflow: hidden; }
.video video { width: 100%; height: 100%; object-fit: contain; }
.video .controls { position: absolute; left: 0; right: 0; bottom: 0; z-index: 5; grid-template-columns: auto auto 1fr auto auto auto auto; grid-template-rows: auto; grid-gap: 10px; padding: 10px; }
/* control buttons styles... */

.playlist { grid-column: 2; grid-row: 1; position: relative; align-content: start; justify-content: center; align-items: start; padding: 20px; grid-template-columns: 1fr 1fr; grid-template-rows: auto 1fr auto; overflow: hidden; }
/* playlist inner styles... */

.video.expand { grid-column: 1 / 3; grid-row: 1; z-index: 2; }
.video.hidesubs .libassjs-canvas-parent { visibility: hidden; }
```
JS code of event when triggering expand mode (video will overlap playlist)
```js
// global...
var videowrap = document.querySelector(".video");
// ...

// event on click expand button:
videowrap.classList.toggle("expand");
```
